# Generated by Django 5.2.7 on 2026-03-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('text', 'Text')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('result', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
