# Generated by Django 5.2.7 on 2026-03-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scanhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
